apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-app
  namespace: container
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: container-app
  template:
    metadata:
      labels:
        app: container-app
    spec:
      containers:
      - name: container-app
        image: containertest123.azurecr.io/containersession:1185
        resources:
          limits:
            memory: "3Gi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: container-secret