apiVersion: v1
kind: Service
metadata:
  name: container-app-service
  namespace: container
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: conatiner-app